net stop msexchangeadtopology /y
net stop msexchangefba /y
net stop msftesql-exchange /y
net stop msexchangeis /y
net stop msexchangesa /y
net stop MSExchangePop3 /y
net stop MSExchangeImap4 /y
net stop iisadmin /y
net stop w3svc /y